version: '1.0'

services:
    db:
        container_name: mysql_database
        image: mysql:8
        ports:
            - "3306:3306"
        volumes:
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: people
            MYSQL_USER: user
            MYSQL_PASSWORD: Advance!23
            MYSQL_ROOT_PASSWORD: Advance!23
volumes:
    mysql-data: